### ISSUE TITLE
خطای ماژول لاگ هنگام اجرا در کنسول

### ISSUE THREAD

**Issue by aminkt** [poshtiban/yii2-user-log#1]

**Comment by aminkt** [comment]
وقتی یک سری پروسه ها در کنسول ران میشوند به واسطه این که برایشان یوزری تعریف نمیشود برای ماژول لاگ مشکل درست میکنند.

خطای زیر هنگام ثبت لاگ در میحط کنسول رخ داده است:

```
#12 {main}yii\base\UnknownMethodException: Calling unknown method: app\components\ConsoleApplication::getUser() in /app/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /app/vendor/poshtiban/yii2-user-log/EventLog.php(52): yii\base\Component->__call('getUser', Array)
#1 /app/models/Event.php(238): poshtiban\yii2\log\EventLog::log('startProcessing', 'app\\models\\Even...')
#2 /app/commands/ProcessorController.php(30): app\models\Event::process(Array)
#3 [internal function]: app\commands\ProcessorController->actionStart(5)
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('start', Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('start', Array)
#8 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('processor/start', Array)
#9 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('processor/start', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /app/yii(44): yii\base\Application->run()
#12 {main}
```

![image](https://user-images.githubusercontent.com/14914854/47266605-d3f04a00-d545-11e8-9594-c75e52e81880.png)
